// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "grqphical",
            "url": "https://github.com/grqphical07"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/grqphical07/rulers-compendium/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/civilizations": {
            "get": {
                "description": "Get's all civilizations available to play in civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Civilizations"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limits amount of results returned",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Civilization"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit value",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/civilizations/{name}": {
            "get": {
                "description": "Gets a civilization in civ 6 based on a given name",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Civilizations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "civilization to get",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Civilization"
                        }
                    }
                }
            }
        },
        "/districts": {
            "get": {
                "description": "Get's all districts from civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Districts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limits amount of results returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filters leaders by civilization",
                        "name": "civilization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.District"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit value",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/districts/{name}": {
            "get": {
                "description": "Gets a district by name in civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Districts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "district to find",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.District"
                        }
                    }
                }
            }
        },
        "/improvements": {
            "get": {
                "description": "Get's all improvements buildable in civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Improvements"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limits amount of results returned",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Improvement"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit value",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/improvements/{name}": {
            "get": {
                "description": "Gets an improvement in civ 6 based on a given name",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Improvements"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Improvement to get",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Improvement"
                        }
                    }
                }
            }
        },
        "/leaders": {
            "get": {
                "description": "Get's all leaders from civ 6 including their agenda's and abilities",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leaders"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limits amount of results returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filters leaders by civilization",
                        "name": "civilization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Leader"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit value",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/leaders/{name}": {
            "get": {
                "description": "Gets a single leader from civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leaders"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "leader to get",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Leader"
                        }
                    }
                }
            }
        },
        "/wonders": {
            "get": {
                "description": "Get's all buildable wonders from civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wonders"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limits amount of results returned",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Wonder"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit value",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wonders/{name}": {
            "get": {
                "description": "Gets a buildable wonder from civ 6",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wonders"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "wonder to get",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.Wonder"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Ability": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "database.Agenda": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "database.Civilization": {
            "type": "object",
            "properties": {
                "ability": {
                    "$ref": "#/definitions/database.Ability"
                },
                "infrastructure": {
                    "type": "string"
                },
                "leaders": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "database.District": {
            "type": "object",
            "properties": {
                "buildings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "exclusive_to": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plunder_yields": {
                    "type": "string"
                }
            }
        },
        "database.Improvement": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "placement": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "plunder": {
                    "type": "string"
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "technology": {
                    "type": "string"
                }
            }
        },
        "database.Leader": {
            "type": "object",
            "properties": {
                "ability": {
                    "$ref": "#/definitions/database.Ability"
                },
                "agenda": {
                    "$ref": "#/definitions/database.Agenda"
                },
                "civ": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "database.Wonder": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "era": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "placement": {
                    "type": "string"
                },
                "production_cost": {
                    "type": "string"
                },
                "requirement": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Rulers Compendium API",
	Description:      "A free-to-use API to access information about Sid Meier's Civilization VI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
