# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, Test and Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  generate_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Get swaggo
      run: go install github.com/swaggo/swag/cmd/swag

    - name: Get Echo-Swagger
      run: go get -v github.com/swaggo/echo-swagger
    - name: Generate Docs
      run: swag init -g main.go --output docs --parseInternal
